/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module time_left_4 (
    input clk,
    input rst,
    input reset_time,
    output reg [7:0] segments,
    output reg times_up
  );
  
  
  
  reg [28:0] M_timer_d, M_timer_q = 1'h0;
  
  wire [8-1:0] M_bin_to_seg_out;
  reg [4-1:0] M_bin_to_seg_bin;
  bin_to_seg_12 bin_to_seg (
    .bin(M_bin_to_seg_bin),
    .out(M_bin_to_seg_out)
  );
  
  always @* begin
    M_timer_d = M_timer_q;
    
    if (reset_time) begin
      M_timer_d = 29'h13ffffff;
      M_bin_to_seg_bin = M_timer_q[25+3-:4];
      times_up = 1'h0;
    end else begin
      if (M_timer_q[0+28-:29] == 29'h00000000) begin
        M_timer_d = 29'h1fffffff;
        M_bin_to_seg_bin = 4'h0;
        times_up = 1'h1;
      end else begin
        M_timer_d = M_timer_q - 1'h1;
        M_bin_to_seg_bin = M_timer_q[25+3-:4];
        if (M_timer_q == 29'h1fffffff) begin
          times_up = 1'h1;
        end else begin
          times_up = 1'h0;
        end
      end
    end
    segments = M_bin_to_seg_out;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_timer_q <= 1'h0;
    end else begin
      M_timer_q <= M_timer_d;
    end
  end
  
endmodule
